In [244]:
import pandas as pd

df = pd.read_csv('Sumatra.csv')

df

,Unnamed: 0,Name,Shape,Elevation,Last eruption (VEI),Geolocation
0,0,Weh,stratovolcano,"617 metres (2,024 ft)",Pleistocene,"5.82, 95.28"
1,1,Seulawah Agam,stratovolcano,"1,810 metres (5,940 ft)",1839 (2),"5.448, 95.658"
2,2,Peuet Sague,complex volcano,"2,801 metres (9,190 ft)",25 December 2000 (2),"4.914, 96.329"
3,3,Geureudong,stratovolcano,"2,885 metres (9,465 ft)",1937,"4.813, 96.82"
4,4,Kembar,shield volcano,"2,245 metres (7,365 ft)",Pleistocene,"3.850, 97.664"
5,5,Sinabung,stratovolcano,"2,460 metres (8,070 ft)",10 August 2020 (2)[12],"3.17, 98.392"
6,6,Toba,supervolcano,"2,157 metres (7,077 ft)",72000 BC,"2.58, 98.83"
7,7,Helatoba-Tarutung,fumarole field,"1,100 metres (3,600 ft)",Pleistocene,"2.03, 98.93"
8,8,Sorikmarapi,stratovolcano,"2,145 metres (7,037 ft)",1986 (1),"0.686, 99.539"
9,9,Marapi,complex volcano,"2,891 metres (9,485 ft)",2018,"-0.381, 100.473"
10,10,Tandikat,stratovolcano,"2,438 metres (7,999 ft)",1924 (1),"-0.433, 100.317"
11,11,Talang,stratovolcano,"2,597 metres (8,520 ft)",12 April 2005 (2),"-0.978, 100.679"
12,12,Kerinci,stratovolcano,"3,800 metres (12,500 ft)",2019 (on going),"-1.697, 101.264"
13,13,Sumbing,stratovolcano,"2,507 metres (8,225 ft)",23 May 1921 (2),"-2.414, 101.728"
14,14,Kaba,stratovolcano,"1,952 metres (6,404 ft)",22 August 2000 (1),"-3.52, 102.62"
15,15,Dempo,stratovolcano,"3,173 metres (10,410 ft)",2018 (1),"-4.03, 103.13"
16,16,Besar,stratovolcano,"1,899 metres (6,230 ft)",April 1940 (1),"-4.43, 103.67"
17,17,Suoh,caldera,"1,000 metres (3,300 ft)",10 July 1933 (4),"-5.25, 104.27"
18,18,Hulubelu,caldera,"1,040 metres (3,410 ft)",1836,"-5.35, 104.60"
19,19,Rajabasa,stratovolcano,"1,281 metres (4,203 ft)",1798,"-5.78, 105.625"

In [207]:
df.drop(df.index[df['Last eruption (VEI)'] == 'unknown'], inplace = True)
df

,Name,Shape,Elevation,Last eruption (VEI),Geolocation
0,Weh,stratovolcano,"617 metres (2,024 ft)",Pleistocene,5°49′N 95°17′E﻿ / ﻿5.82°N 95.28°E﻿ / 5.82; 95.28
1,Seulawah Agam,stratovolcano,"1,810 metres (5,940 ft)",1839 (2),5°26′53″N 95°39′29″E﻿ / ﻿5.448°N 95.658°E﻿ / 5...
2,Peuet Sague,complex volcano,"2,801 metres (9,190 ft)",25 December 2000 (2),4°54′50″N 96°19′44″E﻿ / ﻿4.914°N 96.329°E﻿ / 4...
3,Geureudong,stratovolcano,"2,885 metres (9,465 ft)",1937,4°48′47″N 96°49′12″E﻿ / ﻿4.813°N 96.82°E﻿ / 4....
4,Kembar,shield volcano,"2,245 metres (7,365 ft)",Pleistocene,3°51′00″N 97°39′50″E﻿ / ﻿3.850°N 97.664°E﻿ / 3...
6,Sinabung,stratovolcano,"2,460 metres (8,070 ft)",10 August 2020 (2)[12],3°10′12″N 98°23′31″E﻿ / ﻿3.17°N 98.392°E﻿ / 3....
7,Toba,supervolcano,"2,157 metres (7,077 ft)",72000 BC,2°35′N 98°50′E﻿ / ﻿2.58°N 98.83°E﻿ / 2.58; 98.83
8,Helatoba-Tarutung,fumarole field,"1,100 metres (3,600 ft)",Pleistocene,2°02′N 98°56′E﻿ / ﻿2.03°N 98.93°E﻿ / 2.03; 98.93
12,Sorikmarapi,stratovolcano,"2,145 metres (7,037 ft)",1986 (1),0°41′10″N 99°32′20″E﻿ / ﻿0.686°N 99.539°E﻿ / 0...
15,Marapi,complex volcano,"2,891 metres (9,485 ft)",2018,0°22′52″S 100°28′23″E﻿ / ﻿0.381°S 100.473°E﻿ /...
16,Tandikat,stratovolcano,"2,438 metres (7,999 ft)",1924 (1),0°25′59″S 100°19′01″E﻿ / ﻿0.433°S 100.317°E﻿ /...
17,Talang,stratovolcano,"2,597 metres (8,520 ft)",12 April 2005 (2),0°58′41″S 100°40′44″E﻿ / ﻿0.978°S 100.679°E﻿ /...
18,Kerinci,stratovolcano,"3,800 metres (12,500 ft)",2019 (on going),1°41′49″S 101°15′50″E﻿ / ﻿1.697°S 101.264°E﻿ /...
20,Sumbing,stratovolcano,"2,507 metres (8,225 ft)",23 May 1921 (2),2°24′50″S 101°43′41″E﻿ / ﻿2.414°S 101.728°E﻿ /...
25,Kaba,stratovolcano,"1,952 metres (6,404 ft)",22 August 2000 (1),3°31′S 102°37′E﻿ / ﻿3.52°S 102.62°E﻿ / -3.52; ...
26,Dempo,stratovolcano,"3,173 metres (10,410 ft)",2018 (1),4°02′S 103°08′E﻿ / ﻿4.03°S 103.13°E﻿ / -4.03; ...
29,Besar,stratovolcano,"1,899 metres (6,230 ft)",April 1940 (1),4°26′S 103°40′E﻿ / ﻿4.43°S 103.67°E﻿ / -4.43; ...
32,Suoh,caldera,"1,000 metres (3,300 ft)",10 July 1933 (4),5°15′S 104°16′E﻿ / ﻿5.25°S 104.27°E﻿ / -5.25; ...
33,Hulubelu,caldera,"1,040 metres (3,410 ft)",1836,5°21′S 104°36′E﻿ / ﻿5.35°S 104.60°E﻿ / -5.35; ...
34,Rajabasa,stratovolcano,"1,281 metres (4,203 ft)",1798,5°46′48″S 105°37′30″E﻿ / ﻿5.78°S 105.625°E﻿ / ...

In [208]:
df = df.reset_index(drop = True)
df

,Name,Shape,Elevation,Last eruption (VEI),Geolocation
0,Weh,stratovolcano,"617 metres (2,024 ft)",Pleistocene,5°49′N 95°17′E﻿ / ﻿5.82°N 95.28°E﻿ / 5.82; 95.28
1,Seulawah Agam,stratovolcano,"1,810 metres (5,940 ft)",1839 (2),5°26′53″N 95°39′29″E﻿ / ﻿5.448°N 95.658°E﻿ / 5...
2,Peuet Sague,complex volcano,"2,801 metres (9,190 ft)",25 December 2000 (2),4°54′50″N 96°19′44″E﻿ / ﻿4.914°N 96.329°E﻿ / 4...
3,Geureudong,stratovolcano,"2,885 metres (9,465 ft)",1937,4°48′47″N 96°49′12″E﻿ / ﻿4.813°N 96.82°E﻿ / 4....
4,Kembar,shield volcano,"2,245 metres (7,365 ft)",Pleistocene,3°51′00″N 97°39′50″E﻿ / ﻿3.850°N 97.664°E﻿ / 3...
5,Sinabung,stratovolcano,"2,460 metres (8,070 ft)",10 August 2020 (2)[12],3°10′12″N 98°23′31″E﻿ / ﻿3.17°N 98.392°E﻿ / 3....
6,Toba,supervolcano,"2,157 metres (7,077 ft)",72000 BC,2°35′N 98°50′E﻿ / ﻿2.58°N 98.83°E﻿ / 2.58; 98.83
7,Helatoba-Tarutung,fumarole field,"1,100 metres (3,600 ft)",Pleistocene,2°02′N 98°56′E﻿ / ﻿2.03°N 98.93°E﻿ / 2.03; 98.93
8,Sorikmarapi,stratovolcano,"2,145 metres (7,037 ft)",1986 (1),0°41′10″N 99°32′20″E﻿ / ﻿0.686°N 99.539°E﻿ / 0...
9,Marapi,complex volcano,"2,891 metres (9,485 ft)",2018,0°22′52″S 100°28′23″E﻿ / ﻿0.381°S 100.473°E﻿ /...
10,Tandikat,stratovolcano,"2,438 metres (7,999 ft)",1924 (1),0°25′59″S 100°19′01″E﻿ / ﻿0.433°S 100.317°E﻿ /...
11,Talang,stratovolcano,"2,597 metres (8,520 ft)",12 April 2005 (2),0°58′41″S 100°40′44″E﻿ / ﻿0.978°S 100.679°E﻿ /...
12,Kerinci,stratovolcano,"3,800 metres (12,500 ft)",2019 (on going),1°41′49″S 101°15′50″E﻿ / ﻿1.697°S 101.264°E﻿ /...
13,Sumbing,stratovolcano,"2,507 metres (8,225 ft)",23 May 1921 (2),2°24′50″S 101°43′41″E﻿ / ﻿2.414°S 101.728°E﻿ /...
14,Kaba,stratovolcano,"1,952 metres (6,404 ft)",22 August 2000 (1),3°31′S 102°37′E﻿ / ﻿3.52°S 102.62°E﻿ / -3.52; ...
15,Dempo,stratovolcano,"3,173 metres (10,410 ft)",2018 (1),4°02′S 103°08′E﻿ / ﻿4.03°S 103.13°E﻿ / -4.03; ...
16,Besar,stratovolcano,"1,899 metres (6,230 ft)",April 1940 (1),4°26′S 103°40′E﻿ / ﻿4.43°S 103.67°E﻿ / -4.43; ...
17,Suoh,caldera,"1,000 metres (3,300 ft)",10 July 1933 (4),5°15′S 104°16′E﻿ / ﻿5.25°S 104.27°E﻿ / -5.25; ...
18,Hulubelu,caldera,"1,040 metres (3,410 ft)",1836,5°21′S 104°36′E﻿ / ﻿5.35°S 104.60°E﻿ / -5.35; ...
19,Rajabasa,stratovolcano,"1,281 metres (4,203 ft)",1798,5°46′48″S 105°37′30″E﻿ / ﻿5.78°S 105.625°E﻿ / ...

In [209]:
geolocation = df['Geolocation'].apply(lambda x : x.split('/'))
geolocation

0     [5°49′N 95°17′E﻿ ,  ﻿5.82°N 95.28°E﻿ ,  5.82; ...
1     [5°26′53″N 95°39′29″E﻿ ,  ﻿5.448°N 95.658°E﻿ ,...
2     [4°54′50″N 96°19′44″E﻿ ,  ﻿4.914°N 96.329°E﻿ ,...
3     [4°48′47″N 96°49′12″E﻿ ,  ﻿4.813°N 96.82°E﻿ , ...
4     [3°51′00″N 97°39′50″E﻿ ,  ﻿3.850°N 97.664°E﻿ ,...
5     [3°10′12″N 98°23′31″E﻿ ,  ﻿3.17°N 98.392°E﻿ , ...
6     [2°35′N 98°50′E﻿ ,  ﻿2.58°N 98.83°E﻿ ,  2.58; ...
7     [2°02′N 98°56′E﻿ ,  ﻿2.03°N 98.93°E﻿ ,  2.03; ...
8     [0°41′10″N 99°32′20″E﻿ ,  ﻿0.686°N 99.539°E﻿ ,...
9     [0°22′52″S 100°28′23″E﻿ ,  ﻿0.381°S 100.473°E﻿...
10    [0°25′59″S 100°19′01″E﻿ ,  ﻿0.433°S 100.317°E﻿...
11    [0°58′41″S 100°40′44″E﻿ ,  ﻿0.978°S 100.679°E﻿...
12    [1°41′49″S 101°15′50″E﻿ ,  ﻿1.697°S 101.264°E﻿...
13    [2°24′50″S 101°43′41″E﻿ ,  ﻿2.414°S 101.728°E﻿...
14    [3°31′S 102°37′E﻿ ,  ﻿3.52°S 102.62°E﻿ ,  -3.5...
15    [4°02′S 103°08′E﻿ ,  ﻿4.03°S 103.13°E﻿ ,  -4.0...
16    [4°26′S 103°40′E﻿ ,  ﻿4.43°S 103.67°E﻿ ,  -4.4...
17    [5°15′S 104°16′E﻿ ,  ﻿5.25°S 104.27°E﻿ ,  -5.2...
18    [5°21′S 104°36′E﻿ ,  ﻿5.35°S 104.60°E﻿ ,  -5.3...
19    [5°46′48″S 105°37′30″E﻿ ,  ﻿5.78°S 105.625°E﻿ ...
Name: Geolocation, dtype: object

In [210]:
type(geoloaction)

pandas.core.series.Series

In [211]:
geocoordinates = []
for i in geolocation:
    geocoordinates.append(i[2])
geocoordinates

[' 5.82; 95.28',
 ' 5.448; 95.658',
 ' 4.914; 96.329',
 ' 4.813; 96.82',
 ' 3.850; 97.664',
 ' 3.17; 98.392',
 ' 2.58; 98.83',
 ' 2.03; 98.93',
 ' 0.686; 99.539',
 ' -0.381; 100.473',
 ' -0.433; 100.317',
 ' -0.978; 100.679',
 ' -1.697; 101.264',
 ' -2.414; 101.728',
 ' -3.52; 102.62',
 ' -4.03; 103.13',
 ' -4.43; 103.67',
 ' -5.25; 104.27',
 ' -5.35; 104.60',
 ' -5.78; 105.625']

In [212]:
df['Geolocation'] = pd.DataFrame(geocoordinates)
df

,Name,Shape,Elevation,Last eruption (VEI),Geolocation
0,Weh,stratovolcano,"617 metres (2,024 ft)",Pleistocene,5.82; 95.28
1,Seulawah Agam,stratovolcano,"1,810 metres (5,940 ft)",1839 (2),5.448; 95.658
2,Peuet Sague,complex volcano,"2,801 metres (9,190 ft)",25 December 2000 (2),4.914; 96.329
3,Geureudong,stratovolcano,"2,885 metres (9,465 ft)",1937,4.813; 96.82
4,Kembar,shield volcano,"2,245 metres (7,365 ft)",Pleistocene,3.850; 97.664
5,Sinabung,stratovolcano,"2,460 metres (8,070 ft)",10 August 2020 (2)[12],3.17; 98.392
6,Toba,supervolcano,"2,157 metres (7,077 ft)",72000 BC,2.58; 98.83
7,Helatoba-Tarutung,fumarole field,"1,100 metres (3,600 ft)",Pleistocene,2.03; 98.93
8,Sorikmarapi,stratovolcano,"2,145 metres (7,037 ft)",1986 (1),0.686; 99.539
9,Marapi,complex volcano,"2,891 metres (9,485 ft)",2018,-0.381; 100.473
10,Tandikat,stratovolcano,"2,438 metres (7,999 ft)",1924 (1),-0.433; 100.317
11,Talang,stratovolcano,"2,597 metres (8,520 ft)",12 April 2005 (2),-0.978; 100.679
12,Kerinci,stratovolcano,"3,800 metres (12,500 ft)",2019 (on going),-1.697; 101.264
13,Sumbing,stratovolcano,"2,507 metres (8,225 ft)",23 May 1921 (2),-2.414; 101.728
14,Kaba,stratovolcano,"1,952 metres (6,404 ft)",22 August 2000 (1),-3.52; 102.62
15,Dempo,stratovolcano,"3,173 metres (10,410 ft)",2018 (1),-4.03; 103.13
16,Besar,stratovolcano,"1,899 metres (6,230 ft)",April 1940 (1),-4.43; 103.67
17,Suoh,caldera,"1,000 metres (3,300 ft)",10 July 1933 (4),-5.25; 104.27
18,Hulubelu,caldera,"1,040 metres (3,410 ft)",1836,-5.35; 104.60
19,Rajabasa,stratovolcano,"1,281 metres (4,203 ft)",1798,-5.78; 105.625

In [213]:
df['Geolocation'] = df['Geolocation'].str.replace(';',',',regex= True)

In [214]:
df['Geolocation']

0          5.82, 95.28
1        5.448, 95.658
2        4.914, 96.329
3         4.813, 96.82
4        3.850, 97.664
5         3.17, 98.392
6          2.58, 98.83
7          2.03, 98.93
8        0.686, 99.539
9      -0.381, 100.473
10     -0.433, 100.317
11     -0.978, 100.679
12     -1.697, 101.264
13     -2.414, 101.728
14       -3.52, 102.62
15       -4.03, 103.13
16       -4.43, 103.67
17       -5.25, 104.27
18       -5.35, 104.60
19      -5.78, 105.625
Name: Geolocation, dtype: object

In [215]:
df

,Name,Shape,Elevation,Last eruption (VEI),Geolocation
0,Weh,stratovolcano,"617 metres (2,024 ft)",Pleistocene,"5.82, 95.28"
1,Seulawah Agam,stratovolcano,"1,810 metres (5,940 ft)",1839 (2),"5.448, 95.658"
2,Peuet Sague,complex volcano,"2,801 metres (9,190 ft)",25 December 2000 (2),"4.914, 96.329"
3,Geureudong,stratovolcano,"2,885 metres (9,465 ft)",1937,"4.813, 96.82"
4,Kembar,shield volcano,"2,245 metres (7,365 ft)",Pleistocene,"3.850, 97.664"
5,Sinabung,stratovolcano,"2,460 metres (8,070 ft)",10 August 2020 (2)[12],"3.17, 98.392"
6,Toba,supervolcano,"2,157 metres (7,077 ft)",72000 BC,"2.58, 98.83"
7,Helatoba-Tarutung,fumarole field,"1,100 metres (3,600 ft)",Pleistocene,"2.03, 98.93"
8,Sorikmarapi,stratovolcano,"2,145 metres (7,037 ft)",1986 (1),"0.686, 99.539"
9,Marapi,complex volcano,"2,891 metres (9,485 ft)",2018,"-0.381, 100.473"
10,Tandikat,stratovolcano,"2,438 metres (7,999 ft)",1924 (1),"-0.433, 100.317"
11,Talang,stratovolcano,"2,597 metres (8,520 ft)",12 April 2005 (2),"-0.978, 100.679"
12,Kerinci,stratovolcano,"3,800 metres (12,500 ft)",2019 (on going),"-1.697, 101.264"
13,Sumbing,stratovolcano,"2,507 metres (8,225 ft)",23 May 1921 (2),"-2.414, 101.728"
14,Kaba,stratovolcano,"1,952 metres (6,404 ft)",22 August 2000 (1),"-3.52, 102.62"
15,Dempo,stratovolcano,"3,173 metres (10,410 ft)",2018 (1),"-4.03, 103.13"
16,Besar,stratovolcano,"1,899 metres (6,230 ft)",April 1940 (1),"-4.43, 103.67"
17,Suoh,caldera,"1,000 metres (3,300 ft)",10 July 1933 (4),"-5.25, 104.27"
18,Hulubelu,caldera,"1,040 metres (3,410 ft)",1836,"-5.35, 104.60"
19,Rajabasa,stratovolcano,"1,281 metres (4,203 ft)",1798,"-5.78, 105.625"

In [216]:
df.to_csv('Sumatra.csv')

In [246]:
df.Geolocation = df.Geolocation.apply(lambda x : x.replace(' ','').split(','))
df.Geolocation

AttributeError: 'str' object has no attribute 'int'

In [238]:
#df.Geolocation = df.Geolocation.astype(int)
df.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [247]:
df

,Unnamed: 0,Name,Shape,Elevation,Last eruption (VEI),Geolocation
0,0,Weh,stratovolcano,"617 metres (2,024 ft)",Pleistocene,"5.82, 95.28"
1,1,Seulawah Agam,stratovolcano,"1,810 metres (5,940 ft)",1839 (2),"5.448, 95.658"
2,2,Peuet Sague,complex volcano,"2,801 metres (9,190 ft)",25 December 2000 (2),"4.914, 96.329"
3,3,Geureudong,stratovolcano,"2,885 metres (9,465 ft)",1937,"4.813, 96.82"
4,4,Kembar,shield volcano,"2,245 metres (7,365 ft)",Pleistocene,"3.850, 97.664"
5,5,Sinabung,stratovolcano,"2,460 metres (8,070 ft)",10 August 2020 (2)[12],"3.17, 98.392"
6,6,Toba,supervolcano,"2,157 metres (7,077 ft)",72000 BC,"2.58, 98.83"
7,7,Helatoba-Tarutung,fumarole field,"1,100 metres (3,600 ft)",Pleistocene,"2.03, 98.93"
8,8,Sorikmarapi,stratovolcano,"2,145 metres (7,037 ft)",1986 (1),"0.686, 99.539"
9,9,Marapi,complex volcano,"2,891 metres (9,485 ft)",2018,"-0.381, 100.473"
10,10,Tandikat,stratovolcano,"2,438 metres (7,999 ft)",1924 (1),"-0.433, 100.317"
11,11,Talang,stratovolcano,"2,597 metres (8,520 ft)",12 April 2005 (2),"-0.978, 100.679"
12,12,Kerinci,stratovolcano,"3,800 metres (12,500 ft)",2019 (on going),"-1.697, 101.264"
13,13,Sumbing,stratovolcano,"2,507 metres (8,225 ft)",23 May 1921 (2),"-2.414, 101.728"
14,14,Kaba,stratovolcano,"1,952 metres (6,404 ft)",22 August 2000 (1),"-3.52, 102.62"
15,15,Dempo,stratovolcano,"3,173 metres (10,410 ft)",2018 (1),"-4.03, 103.13"
16,16,Besar,stratovolcano,"1,899 metres (6,230 ft)",April 1940 (1),"-4.43, 103.67"
17,17,Suoh,caldera,"1,000 metres (3,300 ft)",10 July 1933 (4),"-5.25, 104.27"
18,18,Hulubelu,caldera,"1,040 metres (3,410 ft)",1836,"-5.35, 104.60"
19,19,Rajabasa,stratovolcano,"1,281 metres (4,203 ft)",1798,"-5.78, 105.625"

In [250]:
lat = list(df.Geolocation.apply(lambda x : x.replace(' ','').split(',')[0]))
lat

['5.82',
 '5.448',
 '4.914',
 '4.813',
 '3.850',
 '3.17',
 '2.58',
 '2.03',
 '0.686',
 '-0.381',
 '-0.433',
 '-0.978',
 '-1.697',
 '-2.414',
 '-3.52',
 '-4.03',
 '-4.43',
 '-5.25',
 '-5.35',
 '-5.78']

In [252]:
long = list(df.Geolocation.apply(lambda x : x.replace(' ','').split(',')[1]))
long

['95.28',
 '95.658',
 '96.329',
 '96.82',
 '97.664',
 '98.392',
 '98.83',
 '98.93',
 '99.539',
 '100.473',
 '100.317',
 '100.679',
 '101.264',
 '101.728',
 '102.62',
 '103.13',
 '103.67',
 '104.27',
 '104.60',
 '105.625']

In [253]:
elev = df.Elevation.apply(lambda x: x.split(' ')[0])
elev

0       617
1     1,810
2     2,801
3     2,885
4     2,245
5     2,460
6     2,157
7     1,100
8     2,145
9     2,891
10    2,438
11    2,597
12    3,800
13    2,507
14    1,952
15    3,173
16    1,899
17    1,000
18    1,040
19    1,281
Name: Elevation, dtype: object

In [277]:
#last_erp = list(df['Last eruption (VEI)'])
last_erp

['Pleistocene',
 '1839 (2)',
 '25 December 2000 (2)',
 '1937',
 'Pleistocene',
 '10 August 2020 (2)[12]',
 '72000 BC',
 'Pleistocene',
 '1986 (1)',
 '2018',
 '1924 (1)',
 '12 April 2005 (2)',
 '2019 (on going)',
 '23 May 1921 (2)',
 '22 August 2000 (1)',
 '2018 (1)',
 'April 1940 (1)',
 '10 July 1933 (4)',
 '1836',
 '1798']

In [278]:
res = []

for ele in last_erp:
    if 'Pleistocene' == ele or 'BC' in ele:
        res.append('green')
    elif 'ongoing' in ele or 'on going' in ele:
        res.append('red')
    else:
        res.append('orange')
res

['green',
 'orange',
 'orange',
 'orange',
 'green',
 'orange',
 'green',
 'green',
 'orange',
 'orange',
 'orange',
 'orange',
 'red',
 'orange',
 'orange',
 'orange',
 'orange',
 'orange',
 'orange',
 'orange']

In [268]:
employee = {'David':30, 'Esther':35}

In [263]:
sm = [ x+y for x in range(1,3) for y in range(3,6) ]
sm

[4, 5, 6, 5, 6, 7]

In [269]:
 del employee["David"]

In [270]:
employee

{'Esther': 35}

In [271]:
fruits=[['Apple','Orange'],['Mango','Apple']]

print([[fru[x] for fru in fruits] for x in range(2)])

[['Apple', 'Mango'], ['Orange', 'Apple']]

In [272]:
list = [ 1 , 3 , 5 , 8 , 10 , 13 , 18 , 36 , 78 ]

In [273]:
y = [x for x in list[::2] if x%2 == 0]
y

[10, 18, 78]

In [274]:
st="helloworld"

In [275]:
st[0::]

'helloworld'